# Generated by Django 4.2.17 on 2024-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_role_alter_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(db_column='PasswordHash', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Coach', 'Coach')], db_column='Role', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_column='Username', max_length=15, unique=True),
        ),
    ]
