# Generated by Django 4.2.17 on 2024-12-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountsaccount_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=15, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('role', models.CharField(db_column='Role', max_length=6)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
